[package]
name = "knf-rs-sys"
version = "0.1.1"
edition = "2021"
license = "MIT"
description = "fbank features extractor without external dependencies"

[dependencies]

[build-dependencies]
cmake = "0.1.50"
bindgen = "0.69.4"
